import test from "node:test";
import assert from "node:assert/strict";
import { applyDragPosition, createDragSession, resolveSnapPoint } from "../js/glaze.motion.js";

test("drag sessions remain below threshold until meaningful direct manipulation", () => { const drag = createDragSession({ startX: 10, startY: 10, startTime: 0, slopPx: 4 }); const small = drag.update({ x: 12, y: 11, time: 16 }); assert.equal(small.active, false); const active = drag.update({ x: 20, y: 14, time: 32 }); assert.equal(active.active, true); assert.equal(active.deltaX, 10); assert.equal(active.deltaY, 4); assert.ok(active.velocityX > 0); });
test("axis locks preserve intended direct-manipulation direction", () => { const drag = createDragSession({ axis: "x", startTime: 0 }); const snapshot = drag.update({ x: 20, y: 80, time: 20 }); assert.equal(snapshot.deltaX, 20); assert.equal(snapshot.deltaY, 0); assert.equal(snapshot.velocityY, 0); });
test("ended drag sessions cannot accept stale updates", () => { const drag = createDragSession({ startTime: 0 }); const ended = drag.end({ x: 8, y: 0, time: 20 }); assert.equal(ended.ended, true); assert.throws(() => drag.update({ x: 9, y: 0, time: 30 }), /ended drag session/); });
test("snap resolution uses velocity projection without inventing destinations", () => { assert.equal(resolveSnapPoint(45, [0, 50, 100], { velocity: 0 }), 50); assert.equal(resolveSnapPoint(45, [0, 50, 100], { velocity: 0.8 }), 100); assert.equal(resolveSnapPoint(55, [0, 50, 100], { velocity: -0.8 }), 0); });
test("drag application uses CSS variables and explicit dragging state", () => { const properties = new Map(), attributes = new Map(); const element = { style: { setProperty(name, value) { properties.set(name, value); } }, setAttribute(name, value) { attributes.set(name, value); } }; applyDragPosition(element, { deltaX: 14, deltaY: -3, ended: false }); assert.equal(properties.get("--glaze-motion-drag-x"), "14px"); assert.equal(properties.get("--glaze-motion-drag-y"), "-3px"); assert.equal(attributes.get("data-glaze-dragging"), "true"); });
