import test from "node:test";
import assert from "node:assert/strict";
import { applyDragPosition, createDragSession, createPanZoomState, createReorderModel, resolveDirectionalMove, resolveSnapPoint, resolveSwipeAction } from "../js/glaze.motion.js";

test("drag sessions remain below threshold until meaningful direct manipulation", () => { const drag = createDragSession({ startX: 10, startY: 10, startTime: 0, slopPx: 4 }); assert.equal(drag.update({ x: 12, y: 11, time: 16 }).active, false); const active = drag.update({ x: 20, y: 14, time: 32 }); assert.equal(active.active, true); assert.equal(active.deltaX, 10); });
test("axis locks preserve intended direct-manipulation direction", () => { const snapshot = createDragSession({ axis: "x", startTime: 0 }).update({ x: 20, y: 80, time: 20 }); assert.equal(snapshot.deltaX, 20); assert.equal(snapshot.deltaY, 0); });
test("ended drag sessions cannot accept stale updates", () => { const drag = createDragSession({ startTime: 0 }); assert.equal(drag.end({ x: 8, y: 0, time: 20 }).ended, true); assert.throws(() => drag.update({ x: 9, y: 0, time: 30 }), /ended drag session/); });
test("snap resolution uses velocity projection without inventing destinations", () => { assert.equal(resolveSnapPoint(45, [0, 50, 100], { velocity: 0 }), 50); assert.equal(resolveSnapPoint(45, [0, 50, 100], { velocity: 0.8 }), 100); });
test("drag application uses CSS variables and explicit dragging state", () => { const properties = new Map(), attributes = new Map(); const element = { style: { setProperty(name, value) { properties.set(name, value); } }, setAttribute(name, value) { attributes.set(name, value); } }; applyDragPosition(element, { deltaX: 14, deltaY: -3, ended: false }); assert.equal(properties.get("--glaze-motion-drag-x"), "14px"); assert.equal(attributes.get("data-glaze-dragging"), "true"); });
test("swipe resolution uses distance or velocity but returns semantic direction only", () => { assert.equal(resolveSwipeAction(20, 100, { velocity: 0 }), "none"); assert.equal(resolveSwipeAction(40, 100, { velocity: 0 }), "end"); assert.equal(resolveSwipeAction(-10, 100, { velocity: -0.8 }), "start"); });
test("directional mapping provides keyboard and remote reorder parity", () => { assert.equal(resolveDirectionalMove("ArrowUp"), -1); assert.equal(resolveDirectionalMove("ArrowDown"), 1); assert.equal(resolveDirectionalMove("ArrowLeft", { orientation: "horizontal" }), -1); assert.equal(resolveDirectionalMove("Enter"), 0); });
test("reorder model requires stable unique keys and supports non-pointer moves", () => { const model = createReorderModel([{ id: "a" }, { id: "b" }, { id: "c" }]); assert.deepEqual(model.moveByKey("b", "ArrowUp").map((item) => item.id), ["b", "a", "c"]); assert.deepEqual(model.moveBy(0, 99).map((item) => item.id), ["a", "c", "b"]); assert.throws(() => createReorderModel([{ id: "a" }, { id: "a" }]), /unique/); });
test("pan and zoom state clamps scale while preserving the chosen anchor", () => { const state = createPanZoomState({ minScale: 1, maxScale: 3 }); assert.deepEqual(state.panBy(10, 5), { x: 10, y: 5, scale: 1 }); const zoomed = state.zoomTo(2, { anchorX: 10, anchorY: 5 }); assert.deepEqual(zoomed, { x: 10, y: 5, scale: 2 }); assert.equal(state.zoomTo(99).scale, 3); assert.deepEqual(state.reset(), { x: 0, y: 0, scale: 1 }); });
