import test from 'node:test';
import assert from 'node:assert/strict';
import { evaluateMaterialBudget, resolveMaterial, resolvePreferences } from '../js/glaze-2.1.candidate.mjs';

test('Reduced Transparency overrides Clear material personalization',()=>{const p=resolvePreferences({materialClarity:'clear',reducedTransparency:true});assert.equal(p.effectiveMaterialClarity,'solid');assert.equal(resolveMaterial('glaze',p).blurPx,0);});
test('Forced Colors preserves platform authority over accent and material',()=>{const p=resolvePreferences({materialClarity:'clear',forcedColors:true});assert.equal(p.effectiveMaterialClarity,'solid');assert.equal(p.customSemanticColorMapping,'platform');assert.equal(p.accentMayOverridePlatformForcedColors,false);});
test('Reduced Motion resolves expressive motion to calm without changing expression identity',()=>{const p=resolvePreferences({expressionLevel:'expressive',reducedMotion:true});assert.equal(p.expressionLevel,'expressive');assert.equal(p.motionExpression,'calm');});
test('Large Text defeats Compact density when reflow is required',()=>{const p=resolvePreferences({density:'compact',largeText:true,textScalePercent:200});assert.equal(p.effectiveDensity,'standard');assert.equal(p.reflowRequired,true);assert.equal(p.textScalePercent,200);});
test('Touch Assistance raises hit-area floor independently of compact visible density',()=>{const p=resolvePreferences({density:'compact',touchAssistance:true});assert.equal(p.effectiveDensity,'compact');assert.equal(p.touchHitAreaMinPx,56);});
test('Performance profiles bound material blur monotonically',()=>{const full=resolveMaterial('deep-glaze',resolvePreferences({materialClarity:'clear',performanceProfile:'full'})).blurPx;const balanced=resolveMaterial('deep-glaze',resolvePreferences({materialClarity:'clear',performanceProfile:'balanced'})).blurPx;const constrained=resolveMaterial('deep-glaze',resolvePreferences({materialClarity:'clear',performanceProfile:'constrained'})).blurPx;const minimal=resolveMaterial('deep-glaze',resolvePreferences({materialClarity:'clear',performanceProfile:'minimal'})).blurPx;assert.ok(full>=balanced&&balanced>=constrained&&constrained>=minimal);assert.equal(minimal,0);});
test('Productivity Material Budget accepts restrained chrome and rejects excess',()=>{assert.equal(evaluateMaterialBudget({recipe:'productivity',viewportArea:10000,highIntensityArea:1800,deepGlazeSurfaces:1,liveGlazeSurfaces:1}).accepted,true);const bad=evaluateMaterialBudget({recipe:'productivity',viewportArea:10000,highIntensityArea:2800,deepGlazeSurfaces:3,liveGlazeSurfaces:2});assert.equal(bad.accepted,false);assert.ok(bad.reasons.length>=3);});
