import test from "node:test";
import assert from "node:assert/strict";
import { animate, createMotionAdapter, createSharedElementName, createSpringKeyframes, detectCapabilities, prefersReducedMotion, resolveDuration, selectSpatialBackend, setSharedElementName, startSharedTransition } from "../js/glaze.motion.js";

test("reduced-motion detection is dependency-injectable", () => { assert.equal(prefersReducedMotion(() => ({ matches: true })), true); assert.equal(prefersReducedMotion(() => ({ matches: false })), false); });
test("duration roles collapse to zero under reduced motion", () => { assert.equal(resolveDuration("medium", { reducedMotion: false }), 240); assert.equal(resolveDuration("medium", { reducedMotion: true }), 0); assert.throws(() => resolveDuration("unknown"), RangeError); });
test("spring keyframes are deterministic, bounded, and settle on the target", () => { const frames = createSpringKeyframes({ from: 10, to: 20, preset: "standard", samples: 24 }); assert.equal(frames.length, 24); assert.deepEqual(frames[0], { offset: 0, value: 10 }); assert.deepEqual(frames.at(-1), { offset: 1, value: 20 }); assert.ok(frames.every((frame) => Number.isFinite(frame.value))); assert.ok(frames.every((frame) => frame.value >= 9.6 && frame.value <= 20.4)); });
test("animate delegates to Web Animations and strips travel under reduced motion", () => { const calls = []; const element = { animate(keyframes, options) { calls.push({ keyframes, options }); return { cancel() {} }; } }; animate(element, [{ opacity: 0 }, { opacity: 1 }], { durationRole: "short", reducedMotion: true }); assert.equal(calls.length, 1); assert.deepEqual(calls[0].keyframes, [{ opacity: 1 }]); assert.equal(calls[0].options.duration, 0); });
test("component adapters resolve semantic roles and accessibility timing", () => { const dialog = createMotionAdapter("dialog", { reducedMotion: false }); assert.equal(dialog.durationMs, 240); assert.equal(dialog.springPreset, "standard"); assert.equal(createMotionAdapter("dialog", { reducedMotion: true }).durationMs, 0); assert.throws(() => createMotionAdapter("unknown"), RangeError); });
test("shared-element names are stable and reversible", () => { assert.equal(createSharedElementName("message-card_2"), "glaze-message-card_2"); assert.throws(() => createSharedElementName("bad key"), TypeError); const element = { style: { viewTransitionName: "old" } }; const cleanup = setSharedElementName(element, "hero"); assert.equal(element.style.viewTransitionName, "glaze-hero"); cleanup(); assert.equal(element.style.viewTransitionName, "old"); });
test("shared transitions fail safely to immediate state update", () => { let state = 0; const fallback = startSharedTransition(() => { state = 1; return "done"; }, { document: {}, reducedMotion: false }); assert.equal(fallback.usedViewTransition, false); assert.equal(fallback.updateResult, "done"); assert.equal(state, 1); let callback; const transition = { finished: Promise.resolve() }; const supported = startSharedTransition(() => { state = 2; }, { document: { startViewTransition(fn) { callback = fn; return transition; } }, reducedMotion: false }); assert.equal(supported.usedViewTransition, true); assert.equal(supported.transition, transition); callback(); assert.equal(state, 2); });
test("spatial backend selection degrades deterministically", () => { assert.equal(selectSpatialBackend({ webgpu: true, webgl2: true, canvas2d: true }), "webgpu"); assert.equal(selectSpatialBackend({ webgpu: false, webgl2: true, canvas2d: true }), "webgl2"); assert.equal(selectSpatialBackend({ webgpu: false, webgl2: false, canvas2d: true }), "canvas-svg-css"); assert.equal(selectSpatialBackend({ webgpu: false, webgl2: false, canvas2d: false }), "static-accessible"); });
test("capability detection is side-effect free and includes view transitions", () => { const capabilities = detectCapabilities({ navigator: { gpu: {} }, document: { startViewTransition() {} }, WebGL2RenderingContext: class {}, CanvasRenderingContext2D: class {} }); assert.equal(capabilities.webgpu, true); assert.equal(capabilities.webgl2, true); assert.equal(capabilities.canvas2d, true); assert.equal(capabilities.viewTransitions, true); assert.equal(capabilities.webAnimations, false); });
