#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {resolveGlazeExpandedComponent,resolveGlzActivitySurface,resolveGlzAdaptiveToolbar,resolveGlzActionCluster,resolveGlzRecoverySurface,resolveGlzPreferenceGroup,resolveGlzAppearancePicker,resolveGlzThemePreview,resolveGlzColorRolePicker,resolveGlzPalettePreview,resolveGlzAdaptiveSplitView,glazeV17ExpandedComponentSystemDevelopmentContract} from '../js/glaze-v1.7-expanded-component-system.dev.mjs';
import {glazeV17Development} from '../js/glaze-v1.7-development.mjs';
const here=path.dirname(fileURLToPath(import.meta.url));const root=path.resolve(here,'..');const read=r=>fs.readFileSync(path.join(root,r),'utf8');const json=r=>JSON.parse(read(r));const assert=(c,m)=>{if(!c)throw new Error(m);};
const contract=json('contracts/v1.7/expanded-component-system.dev.json');const schema=json('schemas/v1.7-expanded-component-system.schema.json');const tokens=json('tokens/glaze-v1.7-expanded-component-system.dev.json');const lifecycle=json('registry/lifecycle.json');const stable=read('VERSION').trim();const spec=read('GLAZE_UI_V1_7_PLANNED.md');const planned=read('PLANNED-FEATURES.md');const implemented=read('IMPLEMENTED-FEATURES.md');const changelog=read('CHANGELOGS.md');
const components=["GlzAdaptivePane","GlzCommandSurface","GlzActivitySurface","GlzNotificationSurface","GlzAdaptiveToolbar","GlzActionCluster","GlzRecoverySurface","GlzProgressSurface","GlzPreferenceGroup","GlzAppearancePicker","GlzThemePreview","GlzColorRolePicker","GlzPalettePreview","GlzAdaptiveSplitView"];const newComponents=["GlzActivitySurface","GlzAdaptiveToolbar","GlzActionCluster","GlzRecoverySurface","GlzPreferenceGroup","GlzAppearancePicker","GlzThemePreview","GlzColorRolePicker","GlzPalettePreview","GlzAdaptiveSplitView"];
assert(stable==='1.6.0','dev.10 must preserve V1.6 Stable');assert(lifecycle.currentOfficial===stable&&lifecycle.currentStable===stable,'Stable authority mismatch');assert(lifecycle.activeCandidate===null&&lifecycle.activePatchReleaseCandidate===null,'dev.10 must not create Candidate state');assert(lifecycle.plannedNext===null,'dev.10 must not mutate plannedNext');
assert(spec.includes('## 38. Expanded Component System'),'V1.7 v1.2 Section 38 missing');for(const n of components)assert(spec.includes(n),`V1.7 v1.2 Section 38 component missing: ${n}`);assert(spec.includes('dev.8–dev.13 use the prior v1.1 35-section numbering'),'v1.2 plan must preserve v1.1 implementation-numbering provenance');
assert(schema.$schema==='https://json-schema.org/draft/2020-12/schema','schema version mismatch');assert(contract.version==='1.7.0-dev.10','contract version mismatch');assert(contract.lifecycle==='Development'&&contract.consumerEligible===false,'contract lifecycle mismatch');assert(contract.planVersion==='v1.1','plan version mismatch');assert(JSON.stringify(contract.v11SpecificationSections)===JSON.stringify([25]),'Section 25 marker mismatch');assert(JSON.stringify(contract.componentCatalog)===JSON.stringify(components),'component catalog mismatch');assert(JSON.stringify(contract.newComponentFoundations)===JSON.stringify(newComponents),'new component catalog mismatch');assert(contract.semanticRequirements.literalColorInputsAllowed===false&&contract.semanticRequirements.semanticColorRolesRequired===true,'semantic color policy mismatch');assert(contract.acceptanceBoundary.section25Complete===false,'must not claim Section 25 complete');
for(const s of Object.values(contract.integrationFoundations))assert(fs.existsSync(path.join(root,s)),`missing integration: ${s}`);for(const s of Object.values(contract.inheritedComponents))assert(fs.existsSync(path.join(root,s)),`missing inherited source: ${s}`);
assert(tokens.version==='1.7.0-dev.10'&&tokens.consumerEligible===false,'token version/lifecycle mismatch');assert(tokens.semanticColorPolicy.literalColorInputsAllowed===false&&tokens.semanticColorPolicy.semanticColorRolesRequired===true,'token semantic-color policy mismatch');
const base={profile:'mobile',semanticColorRole:'information',semanticProminence:'standard',semanticColorAuthoritative:true,glazeDefaultThemeToken:'glaze.default',previousTaskState:{navigationDestination:'settings',focusId:'appearance',draftText:'preserve',selectionIds:['theme-default']}};
for(const component of components){const x=resolveGlazeExpandedComponent({...base,component});assert(x.component===component,`identity lost: ${component}`);assert(x.presentation.semanticColorRoleRequired===true&&x.presentation.literalColorValueAccepted===false&&x.presentation.colorOnlyMeaningAllowed===false,`semantic presentation boundary lost: ${component}`);assert(x.taskState.navigationDestination==='settings'&&x.taskState.focusId==='appearance'&&x.taskState.draftText==='preserve',`task continuity lost: ${component}`);assert(x.authority.providerTruthCreatedByGlaze===false,`provider truth boundary lost: ${component}`);assert(x.acceptanceBoundary.section25Complete===false,`completion overclaim: ${component}`);}
const resolvers=[resolveGlzActivitySurface,resolveGlzAdaptiveToolbar,resolveGlzActionCluster,resolveGlzRecoverySurface,resolveGlzPreferenceGroup,resolveGlzAppearancePicker,resolveGlzThemePreview,resolveGlzColorRolePicker,resolveGlzPalettePreview,resolveGlzAdaptiveSplitView];for(let i=0;i<resolvers.length;i++)assert(resolvers[i](base).component===newComponents[i],`named resolver mismatch: ${newComponents[i]}`);
const untrusted=resolveGlzRecoverySurface({...base,semanticColorRole:'recovery',providerState:'recoverable',providerStateAuthoritative:false});assert(untrusted.providerState.acceptedState===null&&untrusted.providerState.withheldWithoutAuthority===true,'recovery truth must fail closed');
const trusted=resolveGlzRecoverySurface({...base,semanticColorRole:'recovery',providerState:'recoverable',providerStateAuthoritative:true});assert(trusted.providerState.acceptedState==='recoverable','authoritative recovery truth lost');
for(const bad of ['#ff0000','rgb(255,0,0)','hsl(0 100% 50%)']){let failed=false;try{resolveGlazeExpandedComponent({...base,component:'GlzThemePreview',color:bad});}catch{failed=true;}assert(failed,`literal color accepted: ${bad}`);}
let invalid=false;try{resolveGlazeExpandedComponent({...base,component:'GlzImaginaryThing'});}catch{invalid=true;}assert(invalid,'unknown component must fail closed');
assert(glazeV17ExpandedComponentSystemDevelopmentContract.version==='1.7.0-dev.10'&&glazeV17ExpandedComponentSystemDevelopmentContract.v11SpecificationSections[0]===25,'runtime contract mismatch');assert(glazeV17ExpandedComponentSystemDevelopmentContract.section25Complete===false&&glazeV17ExpandedComponentSystemDevelopmentContract.consumerEligible===false,'runtime lifecycle overclaim');
const aggregateVersionParts=String(glazeV17Development.version).split('-dev.');
const aggregateDevelopmentRevision=Number(aggregateVersionParts[1]);
assert(
  aggregateVersionParts[0]==='1.7.0' && Number.isInteger(aggregateDevelopmentRevision) && aggregateDevelopmentRevision>=10,
  'aggregate Development version must retain or advance beyond Expanded Component System dev.10'
);assert(glazeV17Development.lifecycle==='development'&&glazeV17Development.stableBaseline==='1.6.0'&&glazeV17Development.consumerEligible===false,'aggregate lifecycle mismatch');for(const n of [7,8,9,10,11,12,13,18,19,21,24,25])assert(glazeV17Development.planV11FoundationSections.includes(n),`aggregate missing v1.1 foundation ${n}`);assert(glazeV17Development.expandedComponentSystemFoundation==='js/glaze-v1.7-expanded-component-system.dev.mjs','aggregate missing dev.10');assert(glazeV17Development.nativeGlazeKitsFoundation==='js/glaze-v1.7-native-glaze-kits.dev.mjs','aggregate lost dev.9');assert(glazeV17Development.themeSemanticColorFoundation==='js/glaze-v1.7-theme-semantic-color.dev.mjs','aggregate lost dev.8');assert(glazeV17Development.providerTruthManufactured===false,'provider truth boundary weakened');
assert(planned.includes('1.7.0-dev.10')&&planned.includes('Expanded Component System'),'planned control missing dev.10');assert(planned.includes('1.7.0-dev.9')&&planned.includes('Native Glaze Kits'),'planned control lost dev.9 provenance');assert(implemented.includes('Expanded Component System — `1.7.0-dev.10`'),'implemented control missing dev.10');assert(changelog.includes('1.7.0-dev.10')&&changelog.includes('Expanded Component System'),'changelog missing dev.10');
console.log('GLAZE UI V1.7 Expanded Component System Development foundation: PASS');console.log('Component catalog: 14');console.log('New source foundations: 10');console.log('Section 25 complete: false');console.log('Stable baseline preserved: 1.6.0');console.log('Consumer eligible: false');
